enyo.depends(
	"FeedParser.js",
	"Services.js",
	"App.js",
	"Menu.js",
	"MenuItem.js",
	"SubscriptionsGrid.js",
	"SubscriptionTIle.js",
	"Search.js",
	"PodcastPreview.js",
	"PodcastDetail.js",
	"EpisodeItem.js",
	"Player.js",
	"FilteredList.js",
	"Settings.js"
);